name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: contention/rsync-deployments@v2.0.0
        with:
          FLAGS: -avzr --delete
          EXCLUDES: --exclude .htaccess --exclude .env --exclude /vendor/
          USER: u1651000
          HOST: mafadev.com:65002
          LOCALPATH: /
          REMOTEPATH: /home/u1651000/public_html/dev/smartschool
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
